Update azure-static-web-apps-calm-glacier-00445ad03.yml

diff --git a/.github/workflows/azure-static-web-apps-calm-glacier-00445ad03.yml b/.github/workflows/azure-static-web-apps-calm-glacier-00445ad03.yml
--- a/.github/workflows/azure-static-web-apps-calm-glacier-00445ad03.yml
+++ b/.github/workflows/azure-static-web-apps-calm-glacier-00445ad03.yml
@@ -9,6 +9,15 @@ on:
     branches:
       - main
 
+       name: Check token exists
+  run: |
+    if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_FIELD_02E32AF03 }}" ]; then
+      echo "Token is missing (empty secret)."
+      exit 1
+    else
+      echo "Token is present."
+    fi
+
 jobs:
   build_and_deploy_job:
     if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
@@ -56,3 +65,4 @@ jobs:
         uses: Azure/static-web-apps-deploy@v1
         with:
           action: "close"
+
